# Generated by Django 4.2.20 on 2025-04-14 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0008_docpartilhado_partilhado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departamento', '0003_departamento_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.documento')),
                ('enviar_para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
                ('user_enviou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
