# Generated by Django 4.2.20 on 2025-04-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0004_documentoenviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoenviado',
            name='descricao_de_envio',
            field=models.TextField(default='value'),
            preserve_default=False,
        ),
    ]
