# Generated by Django 4.2.20 on 2025-04-15 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departamento', '0006_documentoenviado_estado_de_aprovacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoenviado',
            name='user_aprovou',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Utilizador_aprovou', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentoenviado',
            name='user_enviou',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='Utilizador_enviou', to=settings.AUTH_USER_MODEL),
        ),
    ]
