# Generated by Django 4.2.20 on 2025-04-08 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Data de Atualicao'),
        ),
        migrations.AddField(
            model_name='documento',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='validated_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Validacao'),
            preserve_default=False,
        ),
    ]
