# Generated by Django 4.2.20 on 2025-04-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0002_documento_created_at_documento_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='texto',
            field=models.TextField(default='Preciso que esse processo avance'),
            preserve_default=False,
        ),
    ]
