# Generated by Django 4.2.20 on 2025-04-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0003_documento_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='documento',
            field=models.FileField(default='page.pdf', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='validated_at',
            field=models.DateField(null=True, verbose_name='Data de Validacao'),
        ),
    ]
