# Generated by Django 4.2.20 on 2025-04-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0004_documento_documento_alter_documento_validated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='validated',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='validated_at',
        ),
        migrations.AddField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('created', 'Criado'), ('sent', 'Enviado para Aprovacao'), ('rejected', 'Rejeitado'), ('aproved', 'Aprovado')], default=('created', 'Criado'), max_length=50),
        ),
        migrations.AddField(
            model_name='documento',
            name='status_at',
            field=models.DateField(null=True, verbose_name='Data do Staus'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.FileField(upload_to='static/'),
        ),
    ]
