# Generated by Django 4.2.20 on 2025-04-09 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0005_remove_documento_validated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocPartilhado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.documento')),
            ],
        ),
    ]
