# Generated by Django 4.2.20 on 2025-04-14 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documento', '0006_docpartilhado'),
    ]

    operations = [
        migrations.AddField(
            model_name='docpartilhado',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='docpartilhado',
            name='partilhado_com',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='utilizador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('created', 'Criado'), ('sent', 'Enviado para Aprovacao'), ('rejected', 'Rejeitado'), ('aproved', 'Aprovado')], default='created', max_length=50),
        ),
    ]
