# Generated by Django 4.2.20 on 2025-04-14 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documento', '0007_docpartilhado_create_at_docpartilhado_partilhado_com_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docpartilhado',
            name='partilhado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Partilhado_Por', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docpartilhado',
            name='partilhado_com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Partilhado_Com', to=settings.AUTH_USER_MODEL),
        ),
    ]
