# Generated by Django 4.2.20 on 2025-04-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0008_docpartilhado_partilhado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
